/*
 * File:   main.c
 * Author: Gavin Delphia
 *
 * Description: This is the main driver program for an implementation of the
 * solitaire encryption algorithm called Pontifex, designed by Bruce Schneier,
 * and featured in Neal Stephenson's 'Cryptonomicon'. Further details are here:
 * http://www.schneier.com/solitaire.html
 *
 * This main function detects command-line arguments and calls appropriate
 * functions defined elsewhere.
 *
 * Prelim Documentation Statement: I did not recieve help on this assignment except for EI with Dr. Bower
 *
 * PEX Documentation Statement: YOUR_PEX_DOCUMENTATION_STATEMENT_HERE
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "deck.h"
#include "files.h"
#include "pontifex.h"

// Since the show_usage function is only used in this file, it's prototype
// is declared here rather than in a separate header file.
void show_usage();

/*
 * Description: The main driver function for this program.
 * Input:       Command line arguments
 * Result:      EXIT_SUCCESS or EXIT_FAILURE
 * PRE:         None.
 * POST:        The appropriate encryption/decryption function will be called.
 */
int main(int argc, char** argv) {
	if (argc == 1) { // Program was executed with no arguments, so show usage.
		show_usage();
	} else if (stricmp(argv[1], "-e") == 0) { // Encrypt
		printf("\nEncrypting...\n");
		if (argc != 5) {
			printf("ERROR: Incorrect number of arguments\n");
			printf(
					"USAGE: pex1_delphia -e deck.txt plaintext.txt encrypted.txt\n");
		} else {
			card_ptr deck = read_deck_from_file(argv[2]);
			encrypt(deck, argv[3], argv[4]);
		}
	} else if (stricmp(argv[1], "-d") == 0) { // Decrypt
		printf("\nDecrypting...\n");
		if (argc != 5) {
			printf("ERROR: Incorrect number of arguments\n");
			printf(
					"USAGE: pex1_delphia -d deck.txt ciphertext.txt decrypted.txt\n");
		} else {
			card_ptr deck = read_deck_from_file(argv[2]);
			decrypt(deck, argv[3], argv[4]);
		}
	} else if (stricmp(argv[1], "-a") == 0) { // Create a new deck with all cards in ascending order
		printf("\nCreating a new ascending order deck...\n");
		if (argc != 3) {
			printf("ERROR: Incorrect number of arguments\n");
			printf("USAGE: pex1_delphia -a deck.txt\n");
		} else {
			card_ptr deck = new_deck();
			printf("Deck: ");
			show_deck(deck);
			//kced_wohs(deck);
			write_deck_to_file(deck, argv[2]);
		}
	} else if (stricmp(argv[1], "-r") == 0) { // Create a new, randomly shuffled deck
		printf("\nCreating a new, randomly shuffled deck...\n");
		if (argc != 3) {
			printf("ERROR: Incorrect number of arguments\n");
			printf("USAGE: pex1_delphia -r deck.txt\n");
		} else {
			card_ptr deck = new_deck();
			deck = shuffle_deck(deck);
			printf("Deck: ");
			show_deck(deck);
			write_deck_to_file(deck, argv[2]);
		}
	} else if (stricmp(argv[1], "-k") == 0) { // Show key sequence
		printf("\nShowing key sequence generated by deck in given file...\n");
		if (argc != 3) {
			printf("ERROR: Incorrect number of arguments\n");
			printf("USAGE: pex1_delphia -k deck.txt\n");
		} else {
			card_ptr deck = read_deck_from_file(argv[2]);
			keyStream(deck, 8);
		}
	} else if (stricmp(argv[1], "-f") == 0) { // Test reading a deck from a file
		printf("\nTesting reading deck from a file...\n");
		if (argc != 3) {
			printf("ERROR: Incorrect number of arguments\n");
			printf("USAGE: pex1_delphia -f deck.txt\n");
		} else {
			card_ptr deck = read_deck_from_file(argv[2]);
			printf("Deck Forward: ");
			show_deck(deck);
			printf("Deck Reverse: ");
			kced_wohs(deck);
		}
	} else if (stricmp(argv[1], "-m") == 0) { // Test move joker steps
		printf("\nTesting move joker steps with deck in given file...\n");
		if (argc != 3) {
			printf("ERROR: Incorrect number of arguments\n");
			printf("USAGE: pex1_delphia -m deck.txt\n");
		} else {
			card_ptr deck = read_deck_from_file(argv[2]);
			printf("Old Deck: ");
			show_deck(deck);
			deck = move_jokers(deck);
			printf("New Deck: ");
			show_deck(deck);
		}
	} else if (stricmp(argv[1], "-t") == 0) { // Test triple cut step
		printf("\nTesting triple cut step with deck in given file...\n");
		if (argc != 3) {
			printf("ERROR: Incorrect number of arguments\n");
			printf("USAGE: pex1_delphia -t deck.txt\n");
		} else {
			card_ptr deck = read_deck_from_file(argv[2]);
			printf("Old Deck: ");
			show_deck(deck);
			deck = triple_cut(deck);
			printf("New Deck: ");
			show_deck(deck);
		}
	} else if (stricmp(argv[1], "-c") == 0) { // Test count cut step
		printf("\nTesting count cut step with deck in given file...\n");
		if (argc != 3) {
			printf("ERROR: Incorrect number of arguments\n");
			printf("USAGE: pex1_delphia -c deck.txt\n");
		} else {
			card_ptr deck = read_deck_from_file(argv[2]);
			printf("Old Deck: ");
			show_deck(deck);
			deck = count_cut(deck);
			printf("New Deck: ");
			show_deck(deck);
		}
	} else if (stricmp(argv[1], "-p") == 0) { // Test entire pontifex algorithm
		printf("\nTesting all pontifex steps with deck in given file...\n");
		if (argc != 3) {
			printf("ERROR: Incorrect number of arguments\n");
			printf("USAGE: pex1_delphia -p deck.txt\n");
		} else {
			card_ptr deck = read_deck_from_file(argv[2]);
			printf("Old Deck: ");
			show_deck(deck);
			deck = move_jokers(deck);
			deck = triple_cut(deck);
			deck = count_cut(deck);
			printf("New Deck: ");
			show_deck(deck);
		}
	} else if (stricmp(argv[1], "-o") == 0) { // Test output card step
		printf("\nTesting find output card step with deck in given file...\n");
		if (argc != 3) {
			printf("ERROR: Incorrect number of arguments\n");
			printf("USAGE: pex1_delphia -o deck.txt\n");
		} else {
			card_ptr deck = read_deck_from_file(argv[2]);
			card_ptr target;
			printf("Deck: ");
			show_deck(deck);
			target = get_outputCard(deck);
			printf("Output Card: %d\n", card_mod(target));
		}
	} else {
		printf("Invalid flag: %s\n", argv[1]);
		show_usage();
		return EXIT_FAILURE;
	}
	return EXIT_SUCCESS;
}

/*
 * Description: Shows the proper usage and command-line arguments for this program.
 * Input:       None.
 * Result:      Usage syntax displayed to user.
 * PRE:         None.
 * POST:        Usage syntax displayed to user.
 */
void show_usage() {
	printf(
			"\nThis program implements the Pontifex encryption scheme designed by Bruce\n");
	printf(
			"Schneier and used in Neal Stephenson's novel 'Cryptonomicon'. This is also\n");
	printf(
			"known as Solitaire Encryption and is described in detail on this web page:\n");
	printf("http://www.schneier.com/solitaire.html\n\n");
	printf("USAGE: \n");
	printf("  To encrypt a message:\n");
	printf("    pex1_delphia -e deck.txt plaintext.txt encrypted.txt\n\n");
	printf("  To decrypt a message:\n");
	printf("    pex1_delphia -d deck.txt ciphertext.txt decrypted.txt\n\n");
	printf("  To create a new deck with cards in ascending order:\n");
	printf("    pex1_delphia -a deck.txt\n\n");
	printf("  To create a new, randomly shuffled deck:\n");
	printf("    pex1_delphia -r deck.txt\n\n");
	printf(
			"  To display the first 8 keys in the key sequence generated by a given deck:\n");
	printf("    pex1_delphia -k deck.txt\n\n");
	printf("  To test reading a deck from a file:\n");
	printf("    pex1_delphia -f deck.txt\n\n");
	printf("  To test move joker steps with the given deck:\n");
	printf("    pex1_delphia -m deck.txt\n\n");
	printf("  To test triple cut step with the given deck:\n");
	printf("    pex1_delphia -t deck.txt\n\n");
	printf("  To test count cut step with the given deck:\n");
	printf("    pex1_delphia -c deck.txt\n\n");
	printf("  To test entire pontifex algorithm with the given deck:\n");
	printf("    pex1_delphia -p deck.txt\n\n");
	printf("  To find the output card with the given deck:\n");
	printf("    pex1_delphia -o deck.txt\n\n");
}
